site_name: Pairrogrammer
site_url: https://github.com/soham901/pairrogrammer
site_description: A mobile app for CS students and project builders to find collaborators using AI-powered matchmaking and gamification.
site_author: Soham Sagathiya

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: orange
      accent: amber
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: orange
      accent: amber
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
  font:
    text: Roboto
    code: Fira Code

nav:
  - Home: index.md
  - Features: features.md
  - Tech Stack: tech_stack.md
  - Contributing: contributing.md
  - License: license.md

extra_css:
  - css/custom.css
extra_javascript:
  - js/custom.js

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - codehilite:
      guess_lang: false
  - fenced_code

plugins:
  - search
  - git-revision-date-localized

page_order:
  - index.md
  - features.md
  - tech_stack.md
  - contributing.md
  - license.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/soham901/pairrogrammer
    - icon: fontawesome/brands/twitter
      link: https://x.com/soham901x
